#!/usr/bin/env node
const cp = require('child_process');

const types = [
    "chore", "docs", "feat", "fix", "refactor", "style", "test"
]


const message = process.title ? process.title.split('-m') : '';

const contains = types.some(type => {
  if (message.indexOf(type) !== -1) {
    console.log(type, message);
    return true;
  }

  return false;
});

if (!contains) {
    console.error("[Error]: Please select an appropriate commit type!");
    console.log("For more information refer to contributing.md file in the root of the folder.");
    process.exit(1);
}